### ISSUE TITLE
perf_event_open: No such file or directory

### ISSUE THREAD

**Issue by jkyunjang** [SlugLab/CXLMemSim#12] opened 2024-06-19 12:09 UTC
Hi there. Thank you for your awesome CXL simulator.

When I run the simulator for 'microbench/malloc' in VirtualBox, I get the error such that "perf_event_open: No such file or directory".

I checked my CPU supports perf, but I couldn't find perf path in my filesystem.

My system info
CPU: Intel(R) Core(TM) Ultra 5 125H
kernel: 5.15.0-107-generic
Dist: Ubuntu 20.04

![image](https://github.com/SlugLab/CXLMemSim/assets/137142685/2b1c227c-aaa4-4d03-b025-d0620e0965f1)

**Comment by ritaru** [comment] 2024-07-02 13:02
This is a duplicate of #10 .

**Closed** 2024-07-03 06:04 UTC
